@MeCorp.Y.Api_HostAddress = http://localhost:5280

GET {{MeCorp.Y.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MeCorp.Y.Api_HostAddress}}/register
Content-Type: application/json

{
  //RegisteredUserRequestDto
}

###

@id=1
GET {{MeCorp.Y.Api_HostAddress}}/api/users/{{id}}

###
